### ISSUE TITLE
社交功能

### ISSUE THREAD

**Issue by NiceKingWei** [awmleer/zju-library#1]
首先给作者赞一个，官方的app确实不是特别好用。我之前也酝酿过类似的app，在这里我想说说我的想法。
* 可以考虑加入社交功能（最简单的当然就是评论和私信）
我上学期借《Haskell编程入门》的时候，发现这本书被人借走了，当时我特别想知道是谁借走了，因为函数式社区比较小，我非常希望能在浙大找到一起学习Haskell的同好。
* 可以考虑接入豆瓣API
通过ISBN可以从豆瓣上拿一些图书信息，返回格式是json
* 我是旧书回流网站的开发者之一，http://book.ckcsu.com
这两个都是与书相关的应用，一个是借图书馆的书，一个是卖二手书，看似没有关联，其实有一定联系。对于我来说，如果我想看一本书，一般是先在豆瓣上搜到，然后考虑要么买，要么借。所以，如果这两个功能能捏在一起，效果应该是不错的。

**Comment by awmleer** [comment]
蟹蟹~

- 现在app的设计是没有后端的，所以如果要实现这个还得另开一套后端的服务😂，过段时间我有空了可以拿Django写一个
- 豆瓣API这个的确之前就在考虑😏
- 竺院的这个旧书回流网站，我很早就被 @RayeRen 安利过了😵（还曾经在上面发布过几本书）啊不过我现在是想让这个app尽可能的精简，专注于某一个细分功能点。。而且book.ckcsu.com似乎是用vue写的，和这个angular的项目不好直接合并。如果你们有兴趣的话，可以考虑在浙图和Good Buy Books上都加上个按钮链接到对方？这样的话可能会帮助到一些同学，也同时保持了各自功能的独立。（<del>其实最主要的是省事😵</del>）
